# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 10:53
from __future__ import unicode_literals

import base.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import newadmin.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
                'permissions': (('pode_cadastrar_solicitacao', 'Pode Cadastrar Solicita\xe7\xe3o'), ('pode_cadastrar_pregao', 'Pode Cadastrar Preg\xe3o'), ('pode_cadastrar_pesquisa_mercadologica', 'Pode Cadastrar Pesquisa Mercadol\xf3gica'), ('pode_ver_minuta', 'Pode Ver Minuta'), ('pode_avaliar_minuta', 'Pode Avaliar Minuta'), ('pode_abrir_processo', 'Pode Abrir Processo'), ('pode_gerenciar_contrato', 'Pode Gerenciar Contrato')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('numero', models.CharField(help_text='No formato: 99999/9999', max_length=100, verbose_name='N\xfamero')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('data_inicio', models.DateField(blank=True, db_column='data_inicio', null=True, verbose_name='Data de In\xedcio')),
                ('data_fim', models.DateField(blank=True, db_column='data_fim', null=True, verbose_name='Data de Vencimento')),
                ('de_prazo', models.BooleanField(default=False, verbose_name='Aditivo de Prazo')),
                ('de_valor', models.BooleanField(default=False, verbose_name='Aditivo de Valor')),
                ('de_fiscal', models.BooleanField(default=False, verbose_name='Aditivo de Fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoAtaRegistroPreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('arquivo', models.FileField(max_length=255, upload_to='upload/pregao/editais/anexos/')),
                ('cadastrado_em', models.DateTimeField(verbose_name='Cadastrado em')),
                ('publico', models.BooleanField(default=False, help_text='Se sim, este documento ser\xe1 exibido publicamente', verbose_name='Documento P\xfablico')),
            ],
            options={
                'verbose_name': 'Anexo da ARP',
                'verbose_name_plural': 'Anexos da ARP',
            },
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('arquivo', models.FileField(max_length=255, upload_to='upload/pregao/editais/anexos/')),
                ('cadastrado_em', models.DateTimeField(verbose_name='Cadastrado em')),
                ('publico', models.BooleanField(default=False, help_text='Se sim, este documento ser\xe1 exibido publicamente', verbose_name='Documento P\xfablico')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo do Contrato',
                'verbose_name_plural': 'Anexos do Contrato',
            },
        ),
        migrations.CreateModel(
            name='AnexoPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('arquivo', models.FileField(max_length=255, upload_to='upload/pregao/editais/anexos/')),
                ('cadastrado_em', models.DateTimeField(verbose_name='Cadastrado em')),
                ('publico', models.BooleanField(default=False, help_text='Se sim, este documento ser\xe1 exibido publicamente', verbose_name='Documento P\xfablico')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo do Preg\xe3o',
                'verbose_name_plural': 'Anexos do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='AtaRegistroPreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='No formato: 99999/9999', max_length=100, verbose_name='N\xfamero')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de In\xedcio')),
                ('data_fim', models.DateField(null=True, verbose_name='Data de Vencimento')),
                ('concluido', models.BooleanField(default=False)),
                ('suspenso', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('dh_cancelamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComissaoLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Portaria')),
            ],
            options={
                'verbose_name': 'Comiss\xe3o de Licita\xe7\xe3o',
                'verbose_name_plural': 'Comiss\xf5es de Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=2000, null=True, verbose_name='Endere\xe7o')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('telefones', models.CharField(help_text='Separar os telefones usando /', max_length=1000, null=True, verbose_name='Telefones')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='upload/logo/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Vari\xe1vel de Configura\xe7\xe3o',
                'verbose_name_plural': 'Vari\xe1veis de Configura\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='No formato: 99999/9999', max_length=100, verbose_name='N\xfamero')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de In\xedcio')),
                ('data_fim', models.DateField(null=True, verbose_name='Data de Vencimento')),
                ('continuado', models.BooleanField(default=False)),
                ('concluido', models.BooleanField(default=False)),
                ('suspenso', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('dh_cancelamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriterioPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Crit\xe9rio de Julgamento do Preg\xe3o',
                'verbose_name_plural': 'Crit\xe9rios de Julgamento de Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='DocumentoSolicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=500, verbose_name='Nome do Arquivo')),
                ('cadastrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Cadastrado Em')),
                ('documento', models.FileField(blank=True, null=True, upload_to=base.models.upload_path_documento, verbose_name='Documento')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_cadastrado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento da Solicita\xe7\xe3o',
                'verbose_name_plural': 'Documentos da Solicita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='DotacaoOrcamentaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dota\xe7\xe3o Or\xe7ament\xe1ria',
                'verbose_name_plural': 'Dota\xe7\xf5es Or\xe7ament\xe1rias',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='Utilize pontos e tra\xe7os.', max_length=255, unique=True, verbose_name='CNPJ/CPF')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Raz\xe3o Social')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endere\xe7o')),
                ('telefones', models.CharField(max_length=300, verbose_name='Telefones')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('banco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ag\xeancia')),
                ('conta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='HistoricoPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('obs', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Observa\xe7\xe3o')),
            ],
            options={
                'ordering': ['data'],
                'verbose_name': 'Hist\xf3rico do Preg\xe3o',
                'verbose_name_plural': 'Hist\xf3ricos do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='InteressadoEdital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Respons\xe1vel')),
                ('nome_empresarial', models.CharField(max_length=200, verbose_name='Nome Empresarial')),
                ('cpf', models.CharField(max_length=80, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=80, verbose_name='CNPK')),
                ('endereco', models.CharField(max_length=80, verbose_name='Endere\xe7o')),
                ('telefone', models.CharField(max_length=80, verbose_name='Telefone')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('interesse', models.CharField(choices=[('Participante', 'Participar da Licita\xe7\xe3o'), ('Interessado', 'Apenas Consulta')], max_length=80, verbose_name='Interesse')),
                ('data_acesso', models.DateTimeField(verbose_name='Data de Acesso')),
            ],
            options={
                'verbose_name': 'Interessado na Licita\xe7\xe3o',
                'verbose_name_plural': 'Interessados na Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='ItemAtaRegistroPreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, null=True, verbose_name='Marca')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AtaRegistroPreco')),
            ],
            options={
                'ordering': ['item__item'],
                'verbose_name': 'Item da ARP',
                'verbose_name_plural': 'Itens da ARP',
            },
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, null=True, verbose_name='Marca')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contrato')),
            ],
            options={
                'ordering': ['item__item'],
                'verbose_name': 'Item do Contrato',
                'verbose_name_plural': 'Itens do Contrato',
            },
        ),
        migrations.CreateModel(
            name='ItemLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(verbose_name='N\xfamero do Item')),
            ],
            options={
                'verbose_name': 'Item do Lote',
                'verbose_name_plural': 'Itens dos Lotes',
            },
        ),
        migrations.CreateModel(
            name='ItemPesquisaMercadologica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255, verbose_name='Marca')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor M\xe1ximo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo da Rejei\xe7\xe3o')),
                ('rejeitado_em', models.DateTimeField(null=True, verbose_name='Rejeitado em')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=500, verbose_name='Unidade de Medida')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_medio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor M\xe9dio')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
            ],
            options={
                'ordering': ['pregao', 'id'],
                'verbose_name': 'Item do Preg\xe3o',
                'verbose_name_plural': 'Itens do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='ItemQuantidadeSecretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('justificativa_reprovacao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo da Nega\xe7\xe3o do Pedido')),
                ('avaliado_em', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado Em')),
                ('avaliado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_avaliado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSolicitacaoLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='Item')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor M\xe9dio')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('situacao', models.CharField(choices=[('Cadastrado', 'Cadastrado'), ('Deserto', 'Deserto'), ('Fracassado', 'Fracassado'), ('Conclu\xeddo', 'Conclu\xeddo')], default='Cadastrado', max_length=50, verbose_name='Situa\xe7\xe3o')),
                ('obs', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Observa\xe7\xe3o')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('eh_lote', models.BooleanField(default=False, verbose_name='Lote')),
            ],
            options={
                'ordering': ['item'],
                'verbose_name': 'Item da Solicita\xe7\xe3o de Licita\xe7\xe3o',
                'verbose_name_plural': 'Itens da Solicita\xe7\xe3o de Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='LanceItemRodadaPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor')),
                ('declinio', models.BooleanField(default=False, verbose_name='Decl\xednio')),
                ('ordem_lance', models.IntegerField(verbose_name='Ordem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao', verbose_name='Item da Solicita\xe7\xe3o')),
            ],
            options={
                'ordering': ['-valor'],
                'verbose_name': 'Lance da Rodada do Preg\xe3o',
                'verbose_name_plural': 'Lances da Rodada do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='LogDownloadArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome Empresarial')),
                ('responsavel', models.CharField(max_length=500, verbose_name='Nome do Respons\xe1vel')),
                ('cpf', models.CharField(max_length=500, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=500, verbose_name='CNPJ Empresarial')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endere\xe7o')),
                ('telefone', models.CharField(max_length=500, verbose_name='Telefone')),
                ('email', models.CharField(max_length=500, verbose_name='Email')),
                ('interesse', models.CharField(choices=[('Participar da Licita\xe7\xe3o', 'Participar da Licita\xe7\xe3o'), ('Apenas Consulta', 'Apenas Consulta')], max_length=100, verbose_name='Interesse')),
                ('baixado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Baixado em')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AnexoPregao')),
            ],
            options={
                'verbose_name': 'Log de Download de Arquivo',
                'verbose_name_plural': 'Logs de Download de Arquivo',
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(help_text='M\xe1ximo de 8000 caracteres.', max_length=8000, unique=True, verbose_name='Nome')),
                ('observacao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observa\xe7\xe3o')),
                ('codigo', models.CharField(blank=True, max_length=6, verbose_name='C\xf3digo')),
            ],
            options={
                'verbose_name': 'Material de Consumo',
                'verbose_name_plural': 'Materiais de Consumo',
            },
        ),
        migrations.CreateModel(
            name='MembroComissaoLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100, verbose_name='Matr\xedcula')),
                ('funcao', models.CharField(choices=[('Apoio', 'Apoio'), ('Membro da CPL', 'Membro da CPL'), ('Membro da Equipe do Preg\xe3o', 'Membro da Equipe do Preg\xe3o'), ('Pregoeiro', 'Pregoeiro'), ('Presidente', 'Presidente')], default='Membro da CPL', max_length=100, verbose_name='Fun\xe7\xe3o')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ComissaoLicitacao')),
            ],
            options={
                'verbose_name': 'Membro da Comiss\xe3o de Licita\xe7\xe3o',
                'verbose_name_plural': 'Membros da Comiss\xe3o de Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='ModalidadePregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Modalidade de Preg\xe3o',
                'verbose_name_plural': 'Modalidades de Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='MovimentoSolicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Enviado Em')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Recebido Em')),
                ('obs', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Observa\xe7\xe3o')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_enviado_por', to=settings.AUTH_USER_MODEL)),
                ('recebido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_recebido_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento da Solicita\xe7\xe3o',
                'verbose_name_plural': 'Movimentos da Solicita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, verbose_name='C\xf3digo IBGE')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Estado')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Munic\xedpio',
                'verbose_name_plural': 'Munic\xedpios',
            },
        ),
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200, verbose_name='N\xfamero da Ordem')),
                ('data', models.DateField(verbose_name='Data')),
                ('projeto_atividade_num', models.CharField(blank=True, max_length=200, null=True, verbose_name='N\xfamero do Projeto de Atividade')),
                ('projeto_atividade_descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descri\xe7\xe3o do Projeto de Atividade')),
                ('programa_num', models.CharField(blank=True, max_length=200, null=True, verbose_name='N\xfamero do Programa')),
                ('programa_descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descri\xe7\xe3o do Programa')),
                ('fonte_num', models.CharField(blank=True, max_length=200, null=True, verbose_name='N\xfamero da Fonte')),
                ('fonte_descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descri\xe7\xe3o da Fonte')),
                ('elemento_despesa_num', models.CharField(blank=True, max_length=200, null=True, verbose_name='N\xfamero do Elemento de Despesa')),
                ('elemento_despesa_descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descri\xe7\xe3o do Elemento de Despesa')),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteItemPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Participante do Item do Preg\xe3o',
                'verbose_name_plural': 'Participantes do Item do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='ParticipantePregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Representante')),
                ('cpf_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF do Representante')),
                ('obs_ausencia_participante', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Motivo da Aus\xeancia do Representante')),
                ('me_epp', models.BooleanField(verbose_name='Micro Empresa/Empresa de Peq.Porte')),
                ('desclassificado', models.BooleanField(default=False, verbose_name='Desclassificado')),
                ('motivo_desclassificacao', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Motivo da Desclassifica\xe7\xe3o')),
                ('arquivo_propostas', models.FileField(blank=True, null=True, upload_to='upload/propostas/', verbose_name='Arquivo com as Propostas')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'ordering': ['desclassificado', 'fornecedor__razao_social'],
                'verbose_name': 'Participante do Preg\xe3o',
                'verbose_name_plural': 'Participantes do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='PedidoAtaRegistroPreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('pedido_em', models.DateTimeField(verbose_name='Pedido em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AtaRegistroPreco')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemAtaRegistroPreco')),
                ('pedido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido da ARP',
                'verbose_name_plural': 'Pedidos da ARP',
            },
        ),
        migrations.CreateModel(
            name='PedidoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('pedido_em', models.DateTimeField(verbose_name='Pedido em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contrato')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemContrato')),
                ('pedido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido do Contrato',
                'verbose_name_plural': 'Pedidos do Contrato',
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('pedido_em', models.DateTimeField(verbose_name='Pedido em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao')),
                ('pedido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido do Item',
                'verbose_name_plural': 'Pedidos do Item',
            },
        ),
        migrations.CreateModel(
            name='PesquisaMercadologica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Raz\xe3o Social')),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endere\xe7o')),
                ('ie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscri\xe7\xe3o Estadual')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('nome_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Representante Legal')),
                ('cpf_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF do Representante Legal')),
                ('rg_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='RG do Representante Legal')),
                ('endereco_representante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endere\xe7o do Representante Legal')),
                ('validade_proposta', models.IntegerField(blank=True, null=True, verbose_name='Dias de Validade da Proposta')),
                ('cadastrada_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio da Proposta')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='upload/pesquisas/', verbose_name='Arquivo da Proposta')),
                ('numero_ata', models.CharField(blank=True, max_length=255, null=True, verbose_name='N\xfamero da Ata')),
                ('vigencia_ata', models.DateField(blank=True, null=True, verbose_name='Vig\xeancia da Ata')),
                ('orgao_gerenciador_ata', models.CharField(blank=True, max_length=255, null=True, verbose_name='\xd3rg\xe3o Gerenciador da Ata')),
                ('origem', models.CharField(blank=True, choices=[('Ata de Registro de Pre\xe7o', 'Ata de Registro de Pre\xe7o'), ('Fornecedor', 'Fornecedor')], max_length=100, null=True, verbose_name='Origem')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(help_text='Digite o CPF com pontos e tra\xe7os.', max_length=15, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('telefones', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefone')),
                ('celulares', models.CharField(blank=True, max_length=60, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=80, null=True, verbose_name='Email')),
                ('cep', newadmin.utils.CepModelField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='N\xfamero')),
                ('complemento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Municipio')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Pregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pregao', models.CharField(max_length=255, verbose_name='N\xfamero do Preg\xe3o')),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de In\xedcio da Retirada das Propostas')),
                ('data_termino', models.DateField(null=True, verbose_name='Data de T\xe9rmino da Retirada das Propostas')),
                ('data_abertura', models.DateField(null=True, verbose_name='Data de Abertura das Propostas')),
                ('hora_abertura', models.TimeField(null=True, verbose_name='Hora de Abertura das Propostas')),
                ('local', models.CharField(max_length=1500, verbose_name='Local')),
                ('responsavel', models.CharField(max_length=255, verbose_name='Respons\xe1vel')),
                ('situacao', models.CharField(choices=[('Cadastrado', 'Cadastrado'), ('Deserto', 'Deserto'), ('Fracassado', 'Fracassado'), ('Suspenso', 'Suspenso'), ('Conclu\xeddo', 'Conclu\xeddo')], default='Cadastrado', max_length=50, verbose_name='Situa\xe7\xe3o')),
                ('obs', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Observa\xe7\xe3o')),
                ('data_adjudicacao', models.DateField(null=True, verbose_name='Data da Adjudica\xe7\xe3o')),
                ('data_homologacao', models.DateField(null=True, verbose_name='Data da Homologa\xe7\xe3o')),
                ('eh_ata_registro_preco', models.BooleanField(default=True, verbose_name='Ata de Registro de Pre\xe7o?')),
                ('arquivo_homologacao', models.FileField(null=True, upload_to=base.models.upload_path_termo_homologacao, verbose_name='Termo de Homologa\xe7\xe3o')),
                ('pode_homologar', models.BooleanField(default=False, verbose_name='Pode Homologar')),
                ('comissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ComissaoLicitacao', verbose_name='Comiss\xe3o de Licita\xe7\xe3o')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CriterioPregao', verbose_name='Crit\xe9rio de Julgamento')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ModalidadePregao', verbose_name='Modalidade')),
                ('ordenador_despesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica', verbose_name='Ordenador de Despesa')),
            ],
            options={
                'verbose_name': 'Preg\xe3o',
                'verbose_name_plural': 'Preg\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=25, unique=True, verbose_name='N\xfamero do Processo')),
                ('objeto', models.CharField(max_length=1500)),
                ('tipo', models.PositiveIntegerField(choices=[[1, 'Memorando'], [2, 'Of\xedcio'], [3, 'Requerimento']])),
                ('status', models.PositiveIntegerField(choices=[[1, 'Em tr\xe2mite'], [2, 'Finalizado'], [3, 'Arquivado']], default=1, verbose_name='Situa\xe7\xe3o')),
                ('palavras_chave', models.TextField(null=True, verbose_name='Palavras-chave')),
                ('data_finalizacao', models.DateTimeField(editable=False, null=True)),
                ('observacao_finalizacao', models.TextField(blank=True, null=True, verbose_name='Despacho')),
                ('pessoa_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_cadastro_set', to=settings.AUTH_USER_MODEL)),
                ('pessoa_finalizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_finalizacao_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='PropostaItemPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('marca', models.CharField(max_length=200, null=True, verbose_name='Marca')),
                ('desclassificado', models.BooleanField(default=False, verbose_name='Desclassificado')),
                ('motivo_desclassificacao', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Motivo da Desclassifica\xe7\xe3o')),
                ('desistencia', models.BooleanField(default=False, verbose_name='Desist\xeancia')),
                ('motivo_desistencia', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Motivo da Desist\xeancia')),
                ('concorre', models.BooleanField(default=True, verbose_name='Concorre')),
                ('valor_item_lote', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Item do Lote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao', verbose_name='Solicita\xe7\xe3o')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ParticipantePregao', verbose_name='Participante')),
                ('pregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao', verbose_name='Preg\xe3o')),
            ],
            options={
                'verbose_name': 'Valor do Item do Preg\xe3o',
                'verbose_name_plural': 'Valores do Item do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='ResultadoItemPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('marca', models.CharField(max_length=200, null=True, verbose_name='Marca')),
                ('ordem', models.IntegerField(verbose_name='Classifica\xe7\xe3o')),
                ('situacao', models.CharField(choices=[('Classificado', 'Classificado'), ('Inabilitado', 'Inabilitado'), ('Desclassificado', 'Desclassificado')], max_length=100, verbose_name='Situa\xe7\xe3o')),
                ('observacoes', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Observa\xe7\xe3o')),
                ('empate', models.BooleanField(default=False, verbose_name='Empate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao', verbose_name='Solicita\xe7\xe3o')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ParticipantePregao', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Resultado da Licita\xe7\xe3o',
                'verbose_name_plural': 'Resultados da Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='RodadaPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField(verbose_name='Rodada de Lances')),
                ('atual', models.BooleanField(default=False, verbose_name='Rodada Atual')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao', verbose_name='Item da Solicita\xe7\xe3o')),
                ('pregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao', verbose_name='Preg\xe3o')),
            ],
            options={
                'verbose_name': 'Rodada do Preg\xe3o',
                'verbose_name_plural': 'Rodadas do Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica', verbose_name='Respons\xe1vel')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Secretaria', verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_memorando', models.CharField(max_length=80, verbose_name='N\xfamero do Memorando')),
                ('objeto', models.TextField(verbose_name='Descri\xe7\xe3o do Objeto')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('situacao', models.CharField(choices=[('Cadastrado', 'Cadastrado'), ('Aguardando Recebimento', 'Aguardando Recebimento'), ('Recebido', 'Recebido'), ('Devolvido', 'Devolvido'), ('Enviado para Licita\xe7\xe3o', 'Enviado para Licita\xe7\xe3o'), ('Em Licita\xe7\xe3o', 'Em Licita\xe7\xe3o'), ('Negada', 'Negada')], default='Cadastrado', max_length=50, verbose_name='Situa\xe7\xe3o')),
                ('tipo', models.CharField(choices=[('Compra', 'Compra'), ('Licita\xe7\xe3o', 'Licita\xe7\xe3o')], default='Licita\xe7\xe3o', max_length=50, verbose_name='Tipo')),
                ('tipo_aquisicao', models.CharField(choices=[('Licita\xe7\xe3o', 'Licita\xe7\xe3o'), ('Dispensa', 'Dispensa'), ('Inexigibilidade', 'Inexigibilidade')], default='Licita\xe7\xe3o', max_length=50, verbose_name='Tipo de Aquisi\xe7\xe3o')),
                ('data_cadastro', models.DateTimeField(verbose_name='Cadastrada em')),
                ('obs_negacao', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Justificativa da Nega\xe7\xe3o')),
                ('data_inicio_pesquisa', models.DateField(blank=True, null=True, verbose_name='In\xedcio das Pesquisas')),
                ('data_fim_pesquisa', models.DateField(blank=True, null=True, verbose_name='Fim das Pesquisas')),
                ('prazo_resposta_interessados', models.DateField(blank=True, null=True, verbose_name='Prazo para retorno dos interessados')),
                ('arquivo_minuta', models.FileField(blank=True, null=True, upload_to='upload/minutas/', verbose_name='Arquivo da Minuta')),
                ('minuta_aprovada', models.BooleanField(default=False, verbose_name='Minuta Aprovada')),
                ('data_avaliacao_minuta', models.DateTimeField(blank=True, null=True, verbose_name='Minuta Aprovada em')),
                ('obs_avaliacao_minuta', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Observa\xe7\xe3o - Minuta')),
                ('arquivo_parecer_minuta', models.FileField(blank=True, null=True, upload_to='upload/minutas/', verbose_name='Arquivo com o Parecer')),
                ('prazo_aberto', models.NullBooleanField(default=False, verbose_name='Aberto para Recebimento de Pesquisa')),
                ('liberada_compra', models.BooleanField(default=False, verbose_name='Liberada para Compra')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interessados', models.ManyToManyField(to='base.Secretaria')),
                ('minuta_avaliada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprova_minuta', to=settings.AUTH_USER_MODEL, verbose_name='Minuta Aprovada Por')),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Processo')),
                ('setor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_atual', to='base.Setor', verbose_name='Setor Atual')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_origem', to='base.Setor', verbose_name='Setor de Origem')),
            ],
            options={
                'verbose_name': 'Solicita\xe7\xe3o de Licita\xe7\xe3o',
                'verbose_name_plural': 'Solicita\xe7\xf5es de Licita\xe7\xe3o',
            },
        ),
        migrations.CreateModel(
            name='TipoPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Preg\xe3o',
                'verbose_name_plural': 'Tipos de Preg\xe3o',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Unidade')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Tipo de Unidade',
                'verbose_name_plural': 'Tipos de Unidade',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Setor', verbose_name='Setor de Origem'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao', verbose_name='Solicita\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TipoPregao', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesquisamercadologica',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='proposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PropostaItemPregao'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='resultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ResultadoItemPregao'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Setor'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='pedidocontrato',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Setor'),
        ),
        migrations.AddField(
            model_name='pedidocontrato',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='pedidoataregistropreco',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Setor'),
        ),
        migrations.AddField(
            model_name='pedidoataregistropreco',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='participantepregao',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao', verbose_name='Preg\xe3o'),
        ),
        migrations.AddField(
            model_name='participanteitempregao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ParticipantePregao', verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='movimentosolicitacao',
            name='setor_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_setor_destino', to='base.Setor'),
        ),
        migrations.AddField(
            model_name='movimentosolicitacao',
            name='setor_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_setor_origem', to='base.Setor'),
        ),
        migrations.AddField(
            model_name='movimentosolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='membrocomissaolicitacao',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='logdownloadarquivo',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Municipio', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='lanceitemrodadapregao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ParticipantePregao', verbose_name='Participante'),
        ),
        migrations.AddField(
            model_name='lanceitemrodadapregao',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RodadaPregao', verbose_name='Rodada'),
        ),
        migrations.AddField(
            model_name='itemsolicitacaolicitacao',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MaterialConsumo'),
        ),
        migrations.AddField(
            model_name='itemsolicitacaolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao', verbose_name='Solicita\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='itemsolicitacaolicitacao',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoUnidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='itemquantidadesecretaria',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='itemquantidadesecretaria',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Secretaria'),
        ),
        migrations.AddField(
            model_name='itemquantidadesecretaria',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao', verbose_name='Solicita\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='itempregao',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MaterialConsumo'),
        ),
        migrations.AddField(
            model_name='itempregao',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao', verbose_name='Preg\xe3o'),
        ),
        migrations.AddField(
            model_name='itempesquisamercadologica',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='itempesquisamercadologica',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PesquisaMercadologica', verbose_name='Pesquisa'),
        ),
        migrations.AddField(
            model_name='itempesquisamercadologica',
            name='rejeitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlote',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_do_lote', to='base.ItemSolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='itemlote',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='base.ItemSolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ParticipantePregao'),
        ),
        migrations.AddField(
            model_name='itemataregistropreco',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='itemataregistropreco',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ParticipantePregao'),
        ),
        migrations.AddField(
            model_name='interessadoedital',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Municipio', verbose_name='Munic\xedpio'),
        ),
        migrations.AddField(
            model_name='interessadoedital',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao'),
        ),
        migrations.AddField(
            model_name='historicopregao',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao'),
        ),
        migrations.AddField(
            model_name='documentosolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao', verbose_name='Solicita\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pregao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Pregao'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Municipio'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='ordenador_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica', verbose_name='Ordenador de Despesa'),
        ),
        migrations.AddField(
            model_name='comissaolicitacao',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Secretaria'),
        ),
        migrations.AddField(
            model_name='ataregistropreco',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao'),
        ),
        migrations.AddField(
            model_name='ataregistropreco',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
        migrations.AddField(
            model_name='ataregistropreco',
            name='usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anexopregao',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao'),
        ),
        migrations.AddField(
            model_name='anexocontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contrato'),
        ),
        migrations.AddField(
            model_name='anexoataregistropreco',
            name='ata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AtaRegistroPreco'),
        ),
        migrations.AddField(
            model_name='anexoataregistropreco',
            name='cadastrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aditivo',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Contrato'),
        ),
    ]
