# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170224_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataregistropreco',
            name='adesao',
            field=models.BooleanField(default=False, verbose_name='Ades\xe3o'),
        ),
        migrations.AddField(
            model_name='ataregistropreco',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Setor'),
        ),
        migrations.AlterField(
            model_name='ataregistropreco',
            name='pregao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Pregao'),
        ),
        migrations.AlterField(
            model_name='ataregistropreco',
            name='solicitacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
    ]
