# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170224_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataregistropreco',
            name='num_oficio',
            field=models.CharField(max_length=100, null=True, verbose_name='N\xfamero do Of\xedcio'),
        ),
        migrations.AddField(
            model_name='ataregistropreco',
            name='objeto',
            field=models.TextField(null=True, verbose_name='Objeto'),
        ),
        migrations.AddField(
            model_name='ataregistropreco',
            name='orgao_origem',
            field=models.CharField(max_length=100, null=True, verbose_name='\xd3rg\xe3o de Origem'),
        ),
    ]
