# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170119_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdownloadarquivo',
            name='baixado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Baixado em'),
        ),
    ]
