# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170224_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ataregistropreco',
            name='setor',
        ),
        migrations.AddField(
            model_name='ataregistropreco',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Secretaria'),
        ),
    ]
