# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_logdownloadarquivo_baixado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdownloadarquivo',
            name='cnpj',
            field=models.CharField(max_length=500, verbose_name='CNPJ Empresarial'),
        ),
        migrations.AlterField(
            model_name='logdownloadarquivo',
            name='responsavel',
            field=models.CharField(max_length=500, verbose_name='Nome do Respons\xe1vel'),
        ),
    ]
