# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170224_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataregistropreco',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
