# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170125_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='pode_homologar',
            field=models.BooleanField(default=False, verbose_name='Pode Homologar'),
        ),
    ]
