# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pregao_pode_homologar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumo',
            name='nome',
            field=models.TextField(help_text='M\xe1ximo de 8000 caracteres.', max_length=8000, unique=True, verbose_name='Nome'),
        ),
    ]
