# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170224_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemataregistropreco',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MaterialConsumo'),
        ),
        migrations.AlterField(
            model_name='itemataregistropreco',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao'),
        ),
    ]
