# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170206_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroComissaoLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portaria', models.CharField(max_length=80, verbose_name='Portaria')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ComissaoLicitacao')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica')),
            ],
            options={
                'verbose_name': 'Membro da Comiss\xe3o de Licita\xe7\xe3o',
                'verbose_name_plural': 'Membros da Comiss\xe3o de Licita\xe7\xe3o',
            },
        ),
    ]
