# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20170224_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumo',
            name='nome',
            field=models.TextField(unique=True, verbose_name='Nome'),
        ),
    ]
