# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_membrocomissaolicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissaolicitacao',
            name='membro',
        ),
        migrations.RemoveField(
            model_name='comissaolicitacao',
            name='portaria',
        ),
    ]
