# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20170208_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='comissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ComissaoLicitacao'),
        ),
    ]
