# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_pregao_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissaolicitacao',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Secretaria'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='comissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ComissaoLicitacao', verbose_name='Comiss\xe3o de Licita\xe7\xe3o'),
        ),
    ]
