# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20170309_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='cnpj',
            field=models.CharField(max_length=200, null=True, verbose_name='CNPJ'),
        ),
    ]
