# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_configuracao_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepregao',
            name='rg_representante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RG do Representante'),
        ),
    ]
