# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170209_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrocomissaolicitacao',
            name='portaria',
        ),
        migrations.AddField(
            model_name='membrocomissaolicitacao',
            name='funcao',
            field=models.CharField(choices=[('Apoio', 'Apoio'), ('Membro da CPL', 'Membro da CPL'), ('Membro da Equipe do Preg\xe3o', 'Membro da Equipe do Preg\xe3o'), ('Pregoeiro', 'Pregoeiro'), ('Presidente', 'Presidente')], default='Membro da CPL', max_length=100, verbose_name='Fun\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='membrocomissaolicitacao',
            name='matricula',
            field=models.CharField(default='111', max_length=100, verbose_name='Matr\xedcula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comissaolicitacao',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Portaria'),
        ),
    ]
