# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_participantepregao_rg_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='cpf_ordenador_despesa',
            field=models.CharField(max_length=200, null=True, verbose_name='CPF do Ordenador de Despesa'),
        ),
    ]
