# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20170209_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='objeto',
            field=models.CharField(max_length=1500),
        ),
    ]
