# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_configuracao_cpf_ordenador_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontrato',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Fornecedor'),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MaterialConsumo'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ParticipantePregao'),
        ),
    ]
