# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20170213_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipounidade',
            options={'ordering': ('nome',), 'verbose_name': 'Tipo de Unidade', 'verbose_name_plural': 'Tipos de Unidade'},
        ),
        migrations.AlterField(
            model_name='solicitacaolicitacao',
            name='justificativa',
            field=models.TextField(verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='solicitacaolicitacao',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='solicitacaolicitacao',
            name='objeto',
            field=models.TextField(verbose_name='Descri\xe7\xe3o do Objeto'),
        ),
    ]
