# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20170314_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemataregistropreco',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoUnidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoUnidade', verbose_name='Unidade'),
        ),
    ]
