# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20170315_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='data_revogacao',
            field=models.DateField(null=True, verbose_name='Data da Revoga\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='situacao',
            field=models.CharField(choices=[('Cadastrado', 'Cadastrado'), ('Deserto', 'Deserto'), ('Fracassado', 'Fracassado'), ('Suspenso', 'Suspenso'), ('Conclu\xeddo', 'Conclu\xeddo'), ('Revogado', 'Revogado')], default='Cadastrado', max_length=50, verbose_name='Situa\xe7\xe3o'),
        ),
    ]
