# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20170320_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='data_suspensao',
            field=models.DateField(null=True, verbose_name='Data da Suspens\xe3o'),
        ),
    ]
