# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_pregao_data_suspensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='cnpj',
            field=models.CharField(max_length=200, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='cpf_ordenador_despesa',
            field=models.CharField(max_length=200, null=True, verbose_name='CPF do Ordenador de Despesa'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='endereco',
            field=models.CharField(max_length=2000, null=True, verbose_name='Endere\xe7o'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='ordenador_despesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretaria_ordenador', to='base.PessoaFisica', verbose_name='Ordenador de Despesa'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='telefones',
            field=models.CharField(help_text='Separar os telefones usando /', max_length=1000, null=True, verbose_name='Telefones'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretaria_responsavel', to='base.PessoaFisica', verbose_name='Respons\xe1vel'),
        ),
    ]
