# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20170324_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempesquisamercadologica',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca'),
        ),
    ]
