# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20170328_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='data_retorno',
            field=models.DateField(null=True, verbose_name='Data do Retorno'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='sine_die',
            field=models.NullBooleanField(verbose_name='Sine Die'),
        ),
    ]
