# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20170330_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='url',
            field=models.CharField(max_length=500, null=True, verbose_name='URL de Acesso'),
        ),
    ]
