# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20170407_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisamercadologica',
            name='validade_proposta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dias de Validade da Proposta'),
        ),
    ]
