# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20170410_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcompra',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao', verbose_name='Solicita\xe7\xe3o'),
        ),
    ]
