# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20170411_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacaolicitacao',
            name='arquivo_referencia_valor_medio',
            field=models.FileField(null=True, upload_to='upload/referencias_valor_medio/', verbose_name='Arquivo com a Refer\xeancia do Valor M\xe9dio'),
        ),
    ]
