# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_itemsolicitacaolicitacao_arquivo_referencia_valor_medio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitantePregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('rg', models.CharField(blank=True, max_length=255, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF')),
                ('pregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Pregao', verbose_name='Preg\xe3o')),
            ],
            options={
                'verbose_name': 'Visitante do Preg\xe3o',
                'verbose_name_plural': 'Visitantes do Preg\xe3o',
            },
        ),
    ]
