# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_visitantepregao_rg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido_por',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='proposta',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='solicitacao',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
