# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20170517_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='objeto_tipo',
            field=models.CharField(choices=[('Compra de Material de Consumo', 'Compra de Material de Consumo'), ('Compra de Material Permanente', 'Compra de Material Permanente'), ('Obras', 'Obras'), ('Servi\xe7os de Engenharia', 'Servi\xe7os de Engenharia'), ('Servi\xe7o de Reforma de Edif\xedcio ou de Equipamento', 'Servi\xe7o de Reforma de Edif\xedcio ou de Equipamento'), ('Servi\xe7os \u2013 Outros', 'Servi\xe7os \u2013 Outros')], default='Compra de Material de Consumo', max_length=200, verbose_name='Objeto - Tipo'),
        ),
    ]
