# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_pregao_objeto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='aplicacao_artigo_57',
            field=models.CharField(blank=True, choices=[('', '---------------'), ('I', 'I - aos projetos cujos produtos estejam contemplados nas metas estabelecidas no Plano Plurianual, os quais poder\xe3o ser prorrogados se houver interesse da Administra\xe7\xe3o e desde que isso tenha sido previsto no ato convocat\xf3rio;'), ('II', 'II - \xe0 presta\xe7\xe3o de servi\xe7os a serem executados de forma cont\xednua, que poder\xe3o ter a sua dura\xe7\xe3o prorrogada por iguais e sucessivos per\xedodos com vistas \xe0 obten\xe7\xe3o de pre\xe7os e condi\xe7\xf5es mais vantajosas para a administra\xe7\xe3o, limitada a sessenta meses; (Reda\xe7\xe3o dada pela Lei n\xba 9.648, de 1998)'), ('IV', 'IV - ao aluguel de equipamentos e \xe0 utiliza\xe7\xe3o de programas de inform\xe1tica, podendo a dura\xe7\xe3o estender-se pelo prazo de at\xe9 48 (quarenta e oito) meses ap\xf3s o in\xedcio da vig\xeancia do contrato.'), ('V', 'V - \xe0s hip\xf3teses previstas nos incisos IX, XIX, XXVIII e XXXI do art. 24, cujos contratos poder\xe3o ter vig\xeancia por at\xe9 120 (cento e vinte) meses, caso haja interesse da administra\xe7\xe3o. (Inclu\xeddo pela Lei n\xba 12.349, de 2010)')], default='', max_length=200, null=True, verbose_name='Aplica\xe7\xe3o do Art. 57 da Lei 8666/93'),
        ),
    ]
