# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20170517_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='eh_ordenadora_despesa',
            field=models.BooleanField(default=True, verbose_name='O respons\xe1vel pela Secretaria \xe9 o Ordenador de Despesa?'),
        ),
    ]
