# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20170517_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='liberada_para_pedido',
            field=models.BooleanField(default=False, verbose_name='Liberada para Pedido'),
        ),
    ]
