# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_solicitacaolicitacao_liberada_para_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopregao',
            name='obs',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
    ]
