# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20170530_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoLCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=5000, verbose_name='Descri\xe7\xe3o')),
            ],
        ),
        migrations.AddField(
            model_name='pregao',
            name='fundamento_legal',
            field=models.CharField(max_length=5000, null=True, verbose_name='Fundamento Legal'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CriterioPregao', verbose_name='Crit\xe9rio de Adjudica\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ModalidadePregao', verbose_name='Modalidade/Procedimento'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TipoPregao', verbose_name='Crit\xe9rio de Julgamento'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='aplicacao_lcn_123_06',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OpcaoLCN', verbose_name='MPE \u2013 Aplica\xe7\xe3o Da LCN 123/06 (Lei 123/06)'),
        ),
    ]
