# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20170605_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='recurso_estadual',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Transferido (Estadual)'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='recurso_federal',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Transferido (Federal)'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='recurso_municipal',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Transferido (Municipal)'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='recurso_proprio',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Pr\xf3prio'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Or\xe7ado'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ModalidadePregao', verbose_name='Modalidade / Procedimento'),
        ),
    ]
