# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20170606_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidadepregao',
            options={'ordering': ['nome'], 'verbose_name': 'Modalidade de Preg\xe3o', 'verbose_name_plural': 'Modalidades de Preg\xe3o'},
        ),
        migrations.AlterField(
            model_name='pregao',
            name='recurso_estadual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Transferido (Estadual)'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='recurso_federal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Transferido (Federal)'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='recurso_municipal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Transferido (Municipal)'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='recurso_proprio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Recurso Pr\xf3prio'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total Or\xe7ado'),
        ),
    ]
