# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20170606_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregao',
            name='situacao',
            field=models.CharField(choices=[('Cadastrado', 'Cadastrado'), ('Deserto', 'Deserto'), ('Fracassado', 'Fracassado'), ('Suspenso', 'Suspenso'), ('Adjudicado', 'Adjudicado'), ('Conclu\xeddo', 'Conclu\xeddo'), ('Revogado', 'Revogado')], default='Cadastrado', max_length=50, verbose_name='Situa\xe7\xe3o'),
        ),
    ]
