# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20170607_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='arp_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arp_da_solicitacao', to='base.AtaRegistroPreco'),
        ),
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='contrato_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato_da_solicitacao', to='base.Contrato'),
        ),
    ]
