# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20170616_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregao',
            name='data_abertura',
            field=models.DateField(null=True, verbose_name='Data de Abertura do Certame'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_inicio',
            field=models.DateField(null=True, verbose_name='Data de In\xedcio da Retirada do Edital'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_termino',
            field=models.DateField(null=True, verbose_name='Data de T\xe9rmino da Retirada do Edial'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='hora_abertura',
            field=models.TimeField(null=True, verbose_name='Hora de Abertura do Certame'),
        ),
    ]
