# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20170622_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoLicitacaoTmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_memorando', models.CharField(max_length=80, verbose_name='N\xfamero do Memorando')),
                ('objeto', models.TextField(verbose_name='Descri\xe7\xe3o do Objeto')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('situacao', models.CharField(choices=[('Cadastrado', 'Cadastrado'), ('Aguardando Recebimento', 'Aguardando Recebimento'), ('Recebido', 'Recebido'), ('Devolvido', 'Devolvido'), ('Enviado para Licita\xe7\xe3o', 'Enviado para Licita\xe7\xe3o'), ('Em Licita\xe7\xe3o', 'Em Licita\xe7\xe3o'), ('Negada', 'Negada')], default='Cadastrado', max_length=50, verbose_name='Situa\xe7\xe3o')),
                ('tipo', models.CharField(choices=[('Compra', 'Compra'), ('Licita\xe7\xe3o', 'Licita\xe7\xe3o')], default='Licita\xe7\xe3o', max_length=50, verbose_name='Tipo')),
                ('tipo_aquisicao', models.CharField(choices=[('Licita\xe7\xe3o', 'Licita\xe7\xe3o'), ('Dispensa', 'Dispensa'), ('Inexigibilidade', 'Inexigibilidade')], default='Licita\xe7\xe3o', max_length=50, verbose_name='Tipo de Aquisi\xe7\xe3o')),
                ('data_cadastro', models.DateTimeField(verbose_name='Cadastrada em')),
                ('arp_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arp_da_solicitacao_tmp', to='base.AtaRegistroPreco')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contrato_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato_da_solicitacao_tmp', to='base.Contrato')),
                ('setor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_atual_tmp', to='base.Setor', verbose_name='Setor Atual')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor_origem_tmp', to='base.Setor', verbose_name='Setor de Origem')),
            ],
            options={
                'verbose_name': 'Solicita\xe7\xe3o Temp',
                'verbose_name_plural': 'Solicita\xe7\xf5es temp',
            },
        ),
    ]
