# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_solicitacaolicitacaotmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditivo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ataregistropreco',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='itempesquisamercadologica',
            name='valor_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor M\xe1ximo'),
        ),
        migrations.AlterField(
            model_name='itempregao',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='itempregao',
            name='valor_medio',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor M\xe9dio'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaolicitacao',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaolicitacao',
            name='valor_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor M\xe9dio'),
        ),
        migrations.AlterField(
            model_name='lanceitemrodadapregao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='propostaitempregao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='propostaitempregao',
            name='valor_item_lote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor do Item do Lote'),
        ),
        migrations.AlterField(
            model_name='resultadoitempregao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
    ]
