# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20170624_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdownloadarquivo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Estado', verbose_name='Estado'),
        ),
    ]
