# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_logdownloadarquivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemataregistropreco',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemcontrato',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itempregao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemquantidadesecretaria',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaolicitacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedidoataregistropreco',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedidocontrato',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade'),
        ),
    ]
