# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 08:59
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20170629_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregao',
            name='aplicacao_lcn_123_06',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OpcaoLCN', verbose_name='MPE \u2013 Aplica\xe7\xe3o Da LCN 123/06 (Lei 123/06)'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='arquivo_homologacao',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_path_termo_homologacao, verbose_name='Termo de Homologa\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ComissaoLicitacao', verbose_name='Comiss\xe3o de Licita\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura do Certame'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_adjudicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Adjudica\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_homologacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Homologa\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de In\xedcio da Retirada do Edital'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Retorno'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_revogacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Revoga\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_suspensao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Suspens\xe3o'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de T\xe9rmino da Retirada do Edial'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='fundamento_legal',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Fundamento Legal'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='hora_abertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Abertura do Certame'),
        ),
        migrations.AlterField(
            model_name='pregao',
            name='ordenador_despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica', verbose_name='Ordenador de Despesa'),
        ),
    ]
