# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20170704_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ataregistropreco',
            name='fornecedor_adesao_arp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_contrato_adesao', to='base.Fornecedor', verbose_name='Fornecedor'),
        ),
    ]
