# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20170717_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregao',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoPregao', verbose_name='Crit\xe9rio de Julgamento'),
        ),
    ]
