# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20170717_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='No formato: 99999/9999', max_length=100, verbose_name='N\xfamero')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de In\xedcio')),
                ('data_fim', models.DateField(null=True, verbose_name='Data de Vencimento')),
                ('concluido', models.BooleanField(default=False)),
                ('suspenso', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('dh_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('orgao_origem', models.CharField(max_length=100, null=True, verbose_name='\xd3rg\xe3o de Origem')),
                ('num_oficio', models.CharField(max_length=100, null=True, verbose_name='N\xfamero do Of\xedcio')),
                ('objeto', models.TextField(null=True, verbose_name='Objeto')),
                ('liberada_compra', models.BooleanField(default=False, verbose_name='Liberada para Compra')),
                ('pregao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Pregao')),
                ('secretaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Secretaria')),
                ('solicitacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao')),
                ('usuario_cancelamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credenciamento',
                'verbose_name_plural': 'Credenciamentos',
            },
        ),
        migrations.CreateModel(
            name='ItemCredenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, null=True, verbose_name='Marca')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade')),
                ('credenciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Credenciamento')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ItemSolicitacaoLicitacao')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MaterialConsumo')),
                ('unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoUnidade', verbose_name='Unidade')),
            ],
            options={
                'ordering': ['item__item'],
                'verbose_name': 'Item do Credenciamento',
                'verbose_name_plural': 'Itens do Credenciamento',
            },
        ),
        migrations.CreateModel(
            name='PedidoCredenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade')),
                ('pedido_em', models.DateTimeField(verbose_name='Pedido em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('credenciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Credenciamento')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemCredenciamento')),
                ('pedido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Setor')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao')),
            ],
            options={
                'verbose_name': 'Pedido do Credenciamento',
                'verbose_name_plural': 'Pedidos do Credenciamento',
            },
        ),
    ]
