# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_credenciamento_itemcredenciamento_pedidocredenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='credenciamento_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credenciamento_da_solicitacao', to='base.Credenciamento'),
        ),
        migrations.AddField(
            model_name='solicitacaolicitacaotmp',
            name='credenciamento_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credenciamento_da_solicitacao_tmp', to='base.Credenciamento'),
        ),
    ]
