# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20170718_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepregao',
            name='excluido_dos_itens',
            field=models.BooleanField(default=False, verbose_name='Exclu\xeddo dos Itens'),
        ),
    ]
