# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_participantepregao_excluido_dos_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoCredenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('arquivo', models.FileField(max_length=255, upload_to='upload/pregao/editais/anexos/')),
                ('cadastrado_em', models.DateTimeField(verbose_name='Cadastrado em')),
                ('publico', models.BooleanField(default=False, help_text='Se sim, este documento ser\xe1 exibido publicamente', verbose_name='Documento P\xfablico')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('credenciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Credenciamento')),
            ],
            options={
                'verbose_name': 'Anexo do Credenciamento',
                'verbose_name_plural': 'Anexos do Credenciamento',
            },
        ),
    ]
