# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_anexocredenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='termo_inexigibilidade',
            field=models.FileField(blank=True, null=True, upload_to='upload/minutas/', verbose_name='Termo de Inexigibilidade'),
        ),
    ]
