# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20170727_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='republicado',
            field=models.BooleanField(default=False, verbose_name='Republicado'),
        ),
    ]
