# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20170727_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedorcrc',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome do Representante Legal'),
        ),
    ]
