# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20170728_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorcrc',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='fornecedorcrc',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfamero'),
        ),
    ]
