# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20170728_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoataregistropreco',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='pedidocontrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='pedidocredenciamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor'),
        ),
    ]
