# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20170731_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aditivo',
            name='numero',
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('', '-----------------'), ('Acr\xe9scimo de Quantitativos', 'Acr\xe9scimo de Quantitativos'), ('Acr\xe9scimo de Valor', 'Acr\xe9scimo de Valor'), ('Reajuste Econ\xf4mico-financeiro', 'Reajuste Econ\xf4mico-financeiro'), ('Supress\xe3o de Quantitativo', 'Supress\xe3o de Quantitativo'), ('Supress\xe3o de Valor', 'Supress\xe3o de Valor')], max_length=50, null=True, verbose_name='Tipo de Aditivo'),
        ),
    ]
