# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20170731_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoItemContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('', '-----------------'), ('Acr\xe9scimo de Quantitativos', 'Acr\xe9scimo de Quantitativos'), ('Acr\xe9scimo de Valor', 'Acr\xe9scimo de Valor'), ('Reajuste Econ\xf4mico-financeiro', 'Reajuste Econ\xf4mico-financeiro'), ('Supress\xe3o de Quantitativo', 'Supress\xe3o de Quantitativo'), ('Supress\xe3o de Valor', 'Supress\xe3o de Valor')], max_length=50, null=True, verbose_name='Tipo de Aditivo')),
                ('indice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\xcdndice de Reajuste')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemContrato')),
            ],
            options={
                'verbose_name': 'Aditivo de Item de Contrato',
                'verbose_name_plural': 'Aditivos de Itens de Contrato',
            },
        ),
    ]
