# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20170803_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontrato',
            name='origem_outro_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato_origem_do_item', to='base.Contrato'),
        ),
    ]
