# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_itemcontrato_origem_outro_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontrato',
            name='origem_outro_contrato',
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='inserido_outro_contrato',
            field=models.BooleanField(default=False, verbose_name='Inserido em Outro Contrato'),
        ),
    ]
