# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20170807_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aditivo',
            options={'ordering': ['ordem'], 'verbose_name': 'Aditivo de Contrato', 'verbose_name_plural': 'Aditivos de Contrato'},
        ),
        migrations.AlterModelOptions(
            name='itemcontrato',
            options={'ordering': ['material__nome'], 'verbose_name': 'Item do Contrato', 'verbose_name_plural': 'Itens do Contrato'},
        ),
    ]
