# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20170809_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretaria',
            options={'ordering': ['nome'], 'verbose_name': 'Secretaria', 'verbose_name_plural': 'Secretarias'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
