# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20170811_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepregao',
            name='credenciado',
            field=models.BooleanField(default=True, verbose_name='Credenciado'),
        ),
    ]
