# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20170818_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemataregistropreco',
            options={'ordering': ['ordem'], 'verbose_name': 'Item da ARP', 'verbose_name_plural': 'Itens da ARP'},
        ),
        migrations.AddField(
            model_name='itemataregistropreco',
            name='ordem',
            field=models.IntegerField(null=True, verbose_name='Ordem'),
        ),
    ]
