# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_auto_20170822_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcontrato',
            options={'ordering': ['ordem'], 'verbose_name': 'Item do Contrato', 'verbose_name_plural': 'Itens do Contrato'},
        ),
        migrations.AlterModelOptions(
            name='itemcredenciamento',
            options={'ordering': ['ordem'], 'verbose_name': 'Item do Credenciamento', 'verbose_name_plural': 'Itens do Credenciamento'},
        ),
        migrations.AddField(
            model_name='itemcontrato',
            name='ordem',
            field=models.IntegerField(null=True, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='itemcredenciamento',
            name='ordem',
            field=models.IntegerField(null=True, verbose_name='Ordem'),
        ),
    ]
