# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_pregao_objeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000, verbose_name='Nome da Ata')),
                ('tipo', models.CharField(choices=[('Ata de Sess\xe3o Inicial', 'Ata de Sess\xe3o Inicial'), ('Ata de Julgamento', 'Ata de Julgamento'), ('Ata de Licita\xe7\xe3o Fracassada', 'Ata de Licita\xe7\xe3o Fracassada'), ('Ata de Licita\xe7\xe3o Deserta', 'Ata de Licita\xe7\xe3o Deserta'), ('Ata de Saneamento', 'Ata de Saneamento')], max_length=100, verbose_name='Tipo da Ata')),
                ('palavras_chaves', models.CharField(max_length=4000, verbose_name='Palavras-Chave')),
                ('cadastrado_em', models.DateTimeField(verbose_name='Cadastrado Em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='upload/minutas/', verbose_name='Arquivo')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica')),
            ],
            options={
                'verbose_name': 'Modelo de Ata',
                'verbose_name_plural': 'Modelos de Atas',
            },
        ),
    ]
