# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_modeloata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloata',
            name='palavras_chaves',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Palavras-Chave'),
        ),
    ]
