# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20170829_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='matricula',
            field=models.CharField(max_length=50, null=True, verbose_name='Matr\xedcula'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='vinculo',
            field=models.CharField(choices=[('Cedido de outra Unidade Administrativa', 'Cedido de outra Unidade Administrativa'), ('Empregado P\xfablico', 'Empregado P\xfablico'), ('Servidor P\xfablico Comissionado', 'Servidor P\xfablico Comissionado'), ('Servidor P\xfablico Efetivo', 'Servidor P\xfablico Efetivo'), ('Servidor Tempor\xe1rio', 'Servidor Tempor\xe1rio'), ('Terceiro estranho \xe0 Administra\xe7\xe3o', 'Terceiro estranho \xe0 Administra\xe7\xe3o')], default='Servidor P\xfablico Efetivo', max_length=200, verbose_name='V\xednculo'),
        ),
    ]
