# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20170901_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissaolicitacao',
            name='data_designacao',
            field=models.DateField(null=True, verbose_name='Data de Designa\xe7\xe3o'),
        ),
    ]
