# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_ordemcompra_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaItemARP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade')),
                ('justificativa', models.CharField(max_length=5000, verbose_name='Justificativa')),
                ('cadastrado_em', models.DateTimeField(verbose_name='Cadastrado em')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ItemAtaRegistroPreco', verbose_name='Item da ARP')),
                ('secretaria_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_destino', to='base.Secretaria', verbose_name='Secretaria de Destino')),
                ('secretaria_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_origem', to='base.Secretaria', verbose_name='Secretaria de Origem')),
            ],
            options={
                'verbose_name': 'Transfer\xeancia de Item de ARP',
                'verbose_name_plural': 'Transfer\xeancias de Itens de ARP',
            },
        ),
        migrations.AlterModelOptions(
            name='pregao',
            options={'ordering': ['-data_abertura'], 'verbose_name': 'Preg\xe3o', 'verbose_name_plural': 'Preg\xf5es'},
        ),
    ]
