# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20170915_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000, verbose_name='Nome do Documento')),
                ('tipo', models.CharField(choices=[('Minuta de Edital', 'Minuta de Edital'), ('Modelo de Edital', 'Modelo de Edital'), ('Modelos de Termo de Refer\xeancia', 'Modelos de Termo de Refer\xeancia'), ('Parecer Jur\xeddico', 'Parecer Jur\xeddico'), ('Minuta de Contrato', 'Minuta de Contrato'), ('Modelo de Rescis\xe3o', 'Modelo de Rescis\xe3o')], max_length=100, verbose_name='Tipo do Documento')),
                ('tipo_objeto', models.CharField(choices=[('Material de Consumo', 'Material de Consumo'), ('Material Permanente', 'Material Permanente'), ('Loca\xe7\xe3o', 'Loca\xe7\xe3o'), ('Publicidade', 'Publicidade'), ('Obras e Manuten\xe7\xe3o', 'Obras e Manuten\xe7\xe3o'), ('Servi\xe7os e Engenharia', 'Servi\xe7os e Engenharia'), ('Servi\xe7os - Outros', 'Servi\xe7os - Outros')], max_length=100, verbose_name='Tipo do Objeto')),
                ('palavras_chaves', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Palavras-Chave')),
                ('cadastrado_em', models.DateTimeField(verbose_name='Cadastrado Em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='upload/modelos_documentos/', verbose_name='Arquivo')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.PessoaFisica')),
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documentos',
            },
        ),
    ]
