# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_modelodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo do Modelo',
                'verbose_name_plural': 'Tipos do Modelo',
            },
        ),
        migrations.CreateModel(
            name='TipoObjetoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Objeto do Modelo',
                'verbose_name_plural': 'Tipos de Objetos do Modelo',
            },
        ),
        migrations.RemoveField(
            model_name='modelodocumento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='modelodocumento',
            name='tipo_objeto',
        ),
    ]
