# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_certidaocrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivo',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Atual'),
        ),
    ]
