# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_aditivo_indice_total_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcompra',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='data_cadastro',
            field=models.DateTimeField(null=True, verbose_name='Cadastrada em'),
        ),
    ]
