# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_auto_20171016_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoSuspensaoPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motivo de Suspens\xe3o do Preg\xe3o',
                'verbose_name_plural': 'Motivos de Suspens\xe3o do Preg\xe3o',
            },
        ),
    ]
