# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_motivosuspensaopregao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPregaoDesconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Preg\xe3o de Desconto',
                'verbose_name_plural': 'Tipos de Preg\xe3o de Desconto',
            },
        ),
        migrations.AddField(
            model_name='pregao',
            name='tipo_desconto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TipoPregaoDesconto', verbose_name='Tipo de Desconto'),
        ),
    ]
