# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_auto_20171030_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='contratacao_global',
            field=models.BooleanField(default=False, verbose_name='Contrata\xe7\xe3o Global (Com pagamentos mensais fixos)'),
        ),
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='numero_meses_contratacao_global',
            field=models.IntegerField(null=True, verbose_name='Informe o N\xfamero de Meses do Contrato'),
        ),
    ]
