# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20171205_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaitempregao',
            name='ordem_inicio',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem do Lance'),
        ),
    ]
