# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_propostaitempregao_ordem_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcompra',
            name='exibe_nome_ordenador',
            field=models.BooleanField(default=True, verbose_name='Incluir Assinatura do Ordenador de Despesa'),
        ),
    ]
