# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_ordemcompra_exibe_nome_ordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedorcrc',
            name='data_expedicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expedi\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='fornecedorcrc',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Natureza Jur\xeddica'),
        ),
    ]
