# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_auto_20180306_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocarSenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=128)),
                ('validade', models.DateTimeField()),
            ],
        ),
    ]
