# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_trocarsenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacaolicitacao',
            name='desconto_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Desconto'),
        ),
    ]
