# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_itemsolicitacaolicitacao_desconto_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrocomissaolicitacao',
            name='funcao',
            field=models.CharField(choices=[('Apoio', 'Apoio'), ('Membro', 'Membro'), ('Membro da Equipe do Preg\xe3o', 'Membro da Equipe do Preg\xe3o'), ('Membro Suplente', 'Membro Suplente'), ('Pregoeiro', 'Pregoeiro'), ('Presidente', 'Presidente')], default='Apoio', max_length=100, verbose_name='Fun\xe7\xe3o'),
        ),
    ]
