# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0105_itemataregistropreco_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='motivo_suspensao',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Motivo da Suspens\xe3o'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='suspenso',
            field=models.BooleanField(default=False, verbose_name='Fornecedor Suspenso'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='suspenso_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Suspenso At\xe9'),
        ),
    ]
