# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0108_auto_20180807_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=300, null=True, verbose_name='Descri\xe7\xe3o')),
                ('recorrente', models.BooleanField(default=False, help_text='Selecione para as datas que ser\xe3o abonadas todos os anos, como feriados nacionais.')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
            },
        ),
    ]
