# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0109_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorcrc',
            name='renovado',
            field=models.BooleanField(default=False, verbose_name='Renovado'),
        ),
    ]
