# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_auto_20180912_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='ordenador_despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenador_despesa', to='base.PessoaFisica', verbose_name='Ordenador de Despesa'),
        ),
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='ordenador_despesa_secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenador_despesa_secretaria', to='base.PessoaFisica', verbose_name='Ordenador de Despesa da Secretaria'),
        ),
        migrations.AddField(
            model_name='solicitacaolicitacao',
            name='responsavel_secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_secretaria', to='base.PessoaFisica', verbose_name='Respons\xe1vel da Secretaria'),
        ),
    ]
