# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_auto_20181030_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissaolicitacao',
            name='tipo',
            field=models.CharField(choices=[('CPL', 'CPL'), ('Preg\xe3o', 'Preg\xe3o')], default='CPL', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='membrocomissaolicitacao',
            name='funcao',
            field=models.CharField(choices=[('Apoio', 'Apoio'), ('Membro', 'Membro'), ('Membro Suplente', 'Membro Suplente'), ('Pregoeiro', 'Pregoeiro'), ('Presidente', 'Presidente')], default='Apoio', max_length=100, verbose_name='Fun\xe7\xe3o'),
        ),
    ]
