# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-24 08:50
from __future__ import unicode_literals

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0116_solicitacaolicitacao_termo_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaolicitacao',
            name='termo_referencia',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_path_termo_referencia, verbose_name='Termo de Refer\xeancia'),
        ),
    ]
