# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-08 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0118_documentosolicitacao_publico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='T\xedtulo do Email')),
                ('destinatarios', models.CharField(max_length=10000, verbose_name='Emails dos Destinat\xe1rios')),
                ('mensagem', models.CharField(max_length=10000, verbose_name='Mensagem do Email')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Enviado',
                'verbose_name_plural': 'Emails Enviados',
            },
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Raz\xe3o Social/Nome'),
        ),
        migrations.AlterField(
            model_name='solicitacaolicitacao',
            name='tipo_aquisicao',
            field=models.CharField(choices=[('Licita\xe7\xe3o', 'Licita\xe7\xe3o'), ('Dispensa', 'Dispensa de Licita\xe7\xe3o (Outros)'), ('Dispensa de Licita\xe7\xe3o (At\xe9 R$ 17.600,00)', 'Dispensa de Licita\xe7\xe3o (At\xe9 R$ 17.600,00 - Aquisi\xe7\xe3o de Bens ou Servi\xe7os Comuns)'), ('Dispensa de Licita\xe7\xe3o (At\xe9 R$ 33.000,00)', 'Dispensa de Licita\xe7\xe3o (At\xe9 R$ 33.000,00 - Obras ou Servi\xe7os de Engenharia)'), ('Inexigibilidade', 'Inexigibilidade de Licita\xe7\xe3o'), ('Credenciamento', 'Credenciamento'), ('Chamada P\xfablica - Alimenta\xe7\xe3o Escolar', 'Chamada P\xfablica - Alimenta\xe7\xe3o Escolar'), ('Chamada P\xfablica - Outros', 'Chamada P\xfablica - Outros'), ('Chamada P\xfablica - PRONATER', 'Chamada P\xfablica - PRONATER')], default='Licita\xe7\xe3o', max_length=50, verbose_name='Tipo de Aquisi\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='solicitacaolicitacaotmp',
            name='tipo_aquisicao',
            field=models.CharField(choices=[('Licita\xe7\xe3o', 'Licita\xe7\xe3o'), ('Dispensa', 'Dispensa de Licita\xe7\xe3o (Outros)'), ('Dispensa de Licita\xe7\xe3o (At\xe9 R$ 17.600,00)', 'Dispensa de Licita\xe7\xe3o (At\xe9 R$ 17.600,00 - Aquisi\xe7\xe3o de Bens ou Servi\xe7os Comuns)'), ('Dispensa de Licita\xe7\xe3o (At\xe9 R$ 33.000,00)', 'Dispensa de Licita\xe7\xe3o (At\xe9 R$ 33.000,00 - Obras ou Servi\xe7os de Engenharia)'), ('Inexigibilidade', 'Inexigibilidade de Licita\xe7\xe3o'), ('Credenciamento', 'Credenciamento'), ('Chamada P\xfablica - Alimenta\xe7\xe3o Escolar', 'Chamada P\xfablica - Alimenta\xe7\xe3o Escolar'), ('Chamada P\xfablica - Outros', 'Chamada P\xfablica - Outros'), ('Chamada P\xfablica - PRONATER', 'Chamada P\xfablica - PRONATER')], default='Licita\xe7\xe3o', max_length=50, verbose_name='Tipo de Aquisi\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.SolicitacaoLicitacao'),
        ),
    ]
