# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_auto_20190308_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregao',
            name='data_abertura_original',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicial de Abertura do Certame'),
        ),
        migrations.AddField(
            model_name='pregao',
            name='hora_abertura_original',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicial de Abertura do Certame'),
        ),
    ]
