# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-13 10:03
from __future__ import unicode_literals

from django.db import migrations

def atualiza_data_abertura(apps, schema_editor):
    Pregao = apps.get_model('base', 'Pregao')


    for pregao in Pregao.objects.all():
        pregao.data_abertura_original = pregao.data_abertura
        pregao.hora_abertura_original = pregao.hora_abertura
        pregao.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0120_auto_20190313_1002'),
    ]

    operations = [
        migrations.RunPython(atualiza_data_abertura),
    ]
