# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0122_auto_20190409_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Municipio'),
        ),
    ]
