# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0123_fornecedor_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquantidadesecretaria',
            name='observacoes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observa\xe7\xf5es'),
        ),
    ]
