# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_itemquantidadesecretaria_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontrato',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
