# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0125_itemcontrato_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcompra',
            name='exibe_nome_secretario',
            field=models.BooleanField(default=True, verbose_name='Incluir Assinatura do Secret\xe1rio'),
        ),
    ]
